### ISSUE TITLE
Microsoft Visual C++ dependency when running `pip install somata`

### ISSUE THREAD

**Issue by tomdstone** [mh105/somata#1]
Windows 10.0.19044

When running `pip install somata` in an empty conda environment, it seems that the `spectrum` package required Microsoft Visual C++ 14.0 or greater, in particular Microsoft C++ Build Tools to be installed.  May be an issue with needing to compile some C code in the compiling.  I was able to get it working by first using `conda install -c conda-forge spectrum` and then `pip install somata`.  Error message below:

![image](https://user-images.githubusercontent.com/77251489/205458208-52d22b6f-316d-4859-9c50-304801c9eb15.png)

**Comment by mh105** [comment]
Should be resolved now with 
```
dependency_links =
    https://conda.anaconda.org/conda-forge/
```
in [setup.cfg](https://github.com/mh105/somata/blob/72c021dc4ca7c4ed59f4e3e044f19539e331dd92/setup.cfg)

**Comment by mh105** [comment]
For clarification and future reference, this was NOT a valid solution because the `conda-forge` channel does not contain wheels or source distributions of `spectrum`. So adding it as the `dependency_links` would not have worked in the first place.

In addition, it is now discouraged to add `dependency_links` or any sort of extra url in package metadata, be it in `setup.cfg` or in the more modern `pyproject.toml`. See here: https://setuptools.pypa.io/en/latest/deprecated/dependency_links.html. So the correct solution in this case can be either of the two:
- Install Microsoft Visual C++ following the link in the error message and `pip install` again will work on Windows
- Install everything from `conda-forge` channel that now distributes `somata`.
